// export const ADD_PARTICIPANT = "ADD_PARTICIPANT";
// export const UPDATE_SELECTED_PARTICIPANT = "UPDATE_SELECTED_PARTICIPANT";
// export const REMOVE_SELECTED_PARTICIPANT = "REMOVE_SELECTED_PARTICIPANT";
// export const GET_ALL_PARTICIPANTS = "GET_ALL_PARTICIPANTS";
// export const GET_SELECTED_PARTICIPANT = "GET_SELECTED_PARTICIPANT";
// export const DISPLAY_MESSAGE = "DISPLAY_MESSAGE";
// export const REDIRECT_TO_SHOW = "REDIRECT_TO_SHOW";
// export const REDIRECT_TO_UPDATE = "REDIRECT_TO_UPDATE";
