// export const PARTICIPANT_ADD = "PARTICIPANT_ADD";
// export const PARTICIPANT_UPDATE = "PARTICIPANT_UPDATE";
// export const PARTICIPANT_DELETE = "PARTICIPANT_DELETE";
// export const PARTICIPANT_SHOW = "PARTICIPANT_SHOW";
// export const PARTICIPANT_SHOW_ALL = "PARTICIPANT_SHOW_ALL";
// export const PARTICIPANT_REDIRECT_TO_UPDATE = "PARTICIPANT_REDIRECT_TO_UPDATE";
// export const PARTICIPANT_DISPLAY_MESSAGE = "PARTICIPANT_DISPLAY_MESSAGE";