export const ADD_COURSE = "ADD_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const GET_ALL_COURSES = "GET_ALL_COURSES";
export const GET_SELECTED_COURSE = "GET_SELECTED_COURSE";
export const REMOVE_SELECTED_COURSE = "REMOVE_SELECTED_COURSE";
export const DISPLAY_MESSAGE = "DISPLAY_MESSAGE";
export const REDIRECT_TO_SHOW = "REDIRECT_TO_SHOW";
export const REDIRECT_TO_UPDATE = "REDIRECT_TO_UPDATE";